name: preprocessing
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - scanpy
  - pandas
  - anndata
  - matplotlib
  - seaborn
  - muon
  - pip:
    - spatialdata
